# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_TR-OYFPmdVbFbB8wMkEwmFQhLLBgDU
"""

import requests
import os

# Substitua 'YOUR_API_KEY' pela sua chave de API do Freesound
API_KEY = 'K56qtx2UEzOYBojhPAq1u8vgD1vgHFIu2NNKwOxc'

def download_sounds(query, num_sounds, save_dir):
    url = f'https://freesound.org/apiv2/search/text/?query={query}&fields=id,name,previews&token={API_KEY}&page_size={num_sounds}'
    response = requests.get(url)
    results = response.json()

    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    for sound in results['results']:
        preview_url = sound['previews']['preview-hq-mp3']
        preview_response = requests.get(preview_url)

        file_path = os.path.join(save_dir, sound['name'] + ".mp3")
        with open(file_path, 'wb') as f:
            f.write(preview_response.content)
        print(f"Baixado: {sound['name']}")

# Baixar sons de diferentes categorias
categories = {
    "bebe_chorando": "baby cry",
    "sirene": "siren",
    "alerta_de_incendio": "fire alarm"
}

# Caminho para salvar os dados
base_dir = 'caminho_para_seus_dados'

for category, query in categories.items():
    save_dir = os.path.join(base_dir, category)
    download_sounds(query, 10, save_dir)  # Baixar 10 sons para cada categoria

print("Download completo!")